// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3GVKt_jIM2el7AB99I0DEDPo5byQ_mtQ',
    appId: '1:41501485294:web:581d52cc027141f783abff',
    messagingSenderId: '41501485294',
    projectId: 'flutter-what-2-grab',
    authDomain: 'flutter-what-2-grab.firebaseapp.com',
    storageBucket: 'flutter-what-2-grab.firebasestorage.app',
    measurementId: 'G-DVE1WKJ0VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pklWYrfwj3Dtqk7oUe_bbgi_ssZSqHU',
    appId: '1:41501485294:android:ab7f25a00493a83a83abff',
    messagingSenderId: '41501485294',
    projectId: 'flutter-what-2-grab',
    storageBucket: 'flutter-what-2-grab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnZEW0-33CicdDF9Ni8YyQ1S-sQrDTjM',
    appId: '1:41501485294:ios:1eee8c86e327316c83abff',
    messagingSenderId: '41501485294',
    projectId: 'flutter-what-2-grab',
    storageBucket: 'flutter-what-2-grab.firebasestorage.app',
    iosBundleId: 'com.example.what2Grab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnZEW0-33CicdDF9Ni8YyQ1S-sQrDTjM',
    appId: '1:41501485294:ios:1eee8c86e327316c83abff',
    messagingSenderId: '41501485294',
    projectId: 'flutter-what-2-grab',
    storageBucket: 'flutter-what-2-grab.firebasestorage.app',
    iosBundleId: 'com.example.what2Grab',
  );
}
