// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:what_2_grab/config/env_key_values.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static get _envValues => EnvKeyValues();

  static FirebaseOptions web = FirebaseOptions(
    apiKey: _envValues.API_KEY_WEB,
    appId: _envValues.APP_ID_WEB,
    messagingSenderId: _envValues.MESSAGING_SENDER_ID,
    projectId: _envValues.PROJECT_ID,
    authDomain: _envValues.AUTH_DOMAIN,
    storageBucket: _envValues.STORAGE_BUCKET,
    measurementId: _envValues.MEASUREMENT_ID,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _envValues.API_KEY_ANDROID,
    appId: _envValues.APP_ID_ANDROID,
    messagingSenderId: _envValues.MESSAGING_SENDER_ID,
    projectId: _envValues.PROJECT_ID,
    storageBucket: _envValues.STORAGE_BUCKET,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _envValues.API_KEY_IOS,
    appId: _envValues.APP_ID_IOS,
    messagingSenderId: _envValues.MESSAGING_SENDER_ID,
    projectId: _envValues.PROJECT_ID,
    storageBucket: _envValues.STORAGE_BUCKET,
    iosBundleId: _envValues.IOS_BUNDLE_ID,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: _envValues.API_KEY_IOS,
    appId: _envValues.APP_ID_IOS,
    messagingSenderId: _envValues.MESSAGING_SENDER_ID,
    projectId: _envValues.PROJECT_ID,
    storageBucket: _envValues.STORAGE_BUCKET,
    iosBundleId: _envValues.IOS_BUNDLE_ID,
  );
}
